import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  // Baseline layout architecture definitions
  splashContainer: {
    flex: 1,
    backgroundColor: "#ffffff",
    justifyContent: "center",
    alignItems: "center",
  },
  logoWrapper: { alignItems: "center" },
  diamondOuter: {
    width: 140,
    height: 140,
    transform: [{ rotate: "45deg" }],
    position: "relative",
    marginBottom: 35,
  },
  diamondBlueHalf: {
    position: "absolute",
    width: "100%",
    height: "50%",
    backgroundColor: "#7ec0ee",
    top: 0,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  diamondGoldHalf: {
    position: "absolute",
    width: "100%",
    height: "50%",
    backgroundColor: "#eebb70",
    bottom: 0,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
  },
  diamondInnerMask: {
    position: "absolute",
    width: "54%",
    height: "54%",
    backgroundColor: "#ffffff",
    top: "23%",
    left: "23%",
  },
  splashMainHeader: {
    fontSize: 24,
    fontWeight: "600",
    color: "#659ec7",
    letterSpacing: 1.5,
  },
  splashSubHeader: {
    fontSize: 70,
    fontWeight: "300",
    color: "#dfb76c",
    letterSpacing: 3,
    lineHeight: 75,
  },

  landingContainer: {
    flex: 1,
    backgroundColor: "#ffffff",
    paddingHorizontal: 30,
    justifyContent: "space-between",
    paddingTop: 60,
    paddingBottom: 50,
  },
  miniBrandRow: { alignItems: "center" },
  miniBrandText: {
    fontSize: 12,
    color: "#95a5a6",
    letterSpacing: 2,
    fontWeight: "600",
  },
  welcomeMessageGroup: { flex: 1, justifyContent: "center" },
  welcomeMainTitle: {
    fontSize: 32,
    fontWeight: "700",
    color: "#2c3e50",
    marginBottom: 15,
  },
  welcomeSubtitle: { fontSize: 16, color: "#7f8c8d", lineHeight: 25 },
  buttonActionGroup: { gap: 15 },
  landingSignInBtn: {
    width: "100%",
    backgroundColor: "#dfb76c",
    borderRadius: 30,
    paddingVertical: 16,
    alignItems: "center",
  },
  landingSignInBtnText: { color: "#ffffff", fontSize: 18, fontWeight: "700" },
  landingRegisterBtn: {
    width: "100%",
    backgroundColor: "#ffffff",
    borderRadius: 30,
    paddingVertical: 16,
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#dfb76c",
  },
  landingRegisterBtnText: { color: "#dfb76c", fontSize: 18, fontWeight: "700" },

  registerScrollContainer: {
    backgroundColor: "#f8f9fa",
    paddingHorizontal: 25,
    paddingTop: 50,
    paddingBottom: 40,
    alignItems: "center",
  },
  registerHeaderZone: {
    width: "100%",
    alignItems: "center",
    borderBottomWidth: 1.5,
    borderColor: "#000000",
    paddingBottom: 10,
    marginBottom: 30,
  },
  registerTitleText: { fontSize: 26, fontWeight: "bold", color: "#000000" },
  formContainer: { width: "100%" },
  fieldLabel: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#000000",
    marginBottom: 5,
  },
  asterisk: { color: "#d63031", fontWeight: "bold" },
  formInput: {
    width: "100%",
    height: 42,
    borderWidth: 1.5,
    borderColor: "#000000",
    borderRadius: 10,
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    marginBottom: 20,
    color: "#000000",
  },
  splitAddressRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  splitFieldColumn: { width: "47%" },
  checkboxRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
    paddingLeft: 2,
  },
  checkboxBox: {
    width: 20,
    height: 20,
    borderWidth: 1.5,
    borderColor: "#000000",
    backgroundColor: "#ffffff",
    marginRight: 12,
  },
  checkboxChecked: { backgroundColor: "#54a0ff" },
  checkboxLabelBlue: { color: "#54a0ff", fontSize: 15 },
  submitButton: {
    width: "100%",
    backgroundColor: "#1b3a6e",
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 25,
    borderWidth: 1,
    borderColor: "#000000",
  },
  submitButtonText: { color: "#ffffff", fontSize: 22, fontWeight: "bold" },

  loginContainer: {
    flex: 1,
    backgroundColor: "#f8f9fa",
    paddingHorizontal: 30,
    justifyContent: "center",
    alignItems: "center",
  },
  topRightRegisterShortcut: {
    position: "absolute",
    top: 50,
    right: 25,
    padding: 5,
  },
  addPersonIcon: { fontSize: 32, color: "#000000" },
  loginLogoZone: { marginBottom: 50 },
  diamondOuterMini: {
    width: 170,
    height: 170,
    transform: [{ rotate: "45deg" }],
    position: "relative",
  },
  loginInputWrapper: {
    width: "100%",
    height: 55,
    borderWidth: 1.5,
    borderColor: "#000000",
    borderRadius: 15,
    backgroundColor: "#ffffff",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 15,
    marginBottom: 25,
  },
  pinInputField: {
    flex: 1,
    height: "100%",
    color: "#000000",
    fontSize: 18,
    fontWeight: "500",
  },
  lockIcon: { fontSize: 20, color: "#000000" },
  loginCoreButton: {
    width: "100%",
    backgroundColor: "#f3c47a",
    borderRadius: 25,
    paddingVertical: 15,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#a4a4a4",
    marginBottom: 20,
  },
  loginCoreButtonText: { color: "#ffffff", fontSize: 20, fontWeight: "bold" },
  forgotPinTouch: { padding: 5 },
  forgotPinText: { color: "#54a0ff", fontSize: 15, fontWeight: "600" },

  dashboardContainer: { flex: 1, backgroundColor: "#eaecee" },
  dashboardScroll: { paddingBottom: 100 },
  bannerImageContainer: {
    width: "100%",
    height: 220,
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderColor: "#bdc3c7",
  },
  bannerImage: { width: "100%", height: "100%" },
  dashboardCardShadow: {
    backgroundColor: "#f2f4f4",
    marginHorizontal: 16,
    marginTop: 18,
    borderRadius: 18,
    padding: 16,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 5,
    borderWidth: 1,
    borderColor: "#d5dbdb",
  },
  actionIconRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  actionIconCell: { alignItems: "center", justifyContent: "center", flex: 1 },
  actionEmoji: { fontSize: 26, color: "#000000", marginBottom: 6 },
  actionIconCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    borderWidth: 1.5,
    borderColor: "#000000",
  },
  actionIconCircleGold: { backgroundColor: "#f3c47a" },
  actionIconCircleBlue: { backgroundColor: "#54a0ff" },
  actionIconCircleNavy: { backgroundColor: "#1b3a6e" },
  actionIconCircleGreen: { backgroundColor: "#2ecc71" },
  actionText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#000000",
    textAlign: "center",
  },
  verifiedAccountsContainer: { width: "100%", paddingVertical: 4 },
  verifiedTitleText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#000000",
    marginBottom: 8,
  },
  bankNameText: {
    fontSize: 15,
    fontWeight: "500",
    color: "#2c3e50",
    marginLeft: 6,
    lineHeight: 24,
  },
  bankAccountRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  bankBalanceText: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#2ecc71",
  },
  metricsContainerRow: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    justifyContent: "space-between",
    paddingVertical: 6,
  },
  networthCircleRing: {
    width: 105,
    height: 105,
    borderRadius: 52.5,
    borderWidth: 2,
    borderColor: "#000000",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  networthLabel: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#000000",
    marginBottom: 2,
  },
  networthValue: { fontSize: 16, fontWeight: "bold", color: "#000000" },
  metricsTextBlock: { flex: 1, paddingLeft: 25, justifyContent: "center" },
  metricItemLabel: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#000000",
    marginBottom: 4,
  },
  metricUnderlineDivider: {
    width: "90%",
    height: 3,
    backgroundColor: "#000000",
    marginBottom: 16,
  },

  bottomTabBarRow: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 70,
    backgroundColor: "#f2f4f4",
    borderTopWidth: 1.5,
    borderColor: "#bdc3c7",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingBottom: 8,
  },
  tabBarButton: { padding: 10, alignItems: "center", justifyContent: "center" },
  tabBarButtonActive: {
    padding: 10,
    alignItems: "center",
    justifyContent: "center",
    borderBottomWidth: 3,
    borderBottomColor: "#659ec7",
  },
  tabBarIcon: { fontSize: 26, color: "#000000" },

  addCardContainer: { flex: 1, backgroundColor: "#f8f9fa" },
  addCardHeaderZone: {
    width: "100%",
    paddingTop: 60,
    paddingBottom: 15,
    alignItems: "center",
    borderBottomWidth: 1.5,
    borderColor: "#000000",
    backgroundColor: "#f8f9fa",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
  },
  backArrowTouchLeft: { paddingHorizontal: 8, paddingVertical: 4 },
  addCardTitleText: { fontSize: 24, fontWeight: "bold", color: "#000000" },
  addCardFormWrapper: {
    paddingHorizontal: 24,
    paddingTop: 30,
    paddingBottom: 100,
  },
  greyCardDataBox: {
    width: "100%",
    backgroundColor: "#dcdde1",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 24,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#b2bec3",
  },
  cardNoInputRow: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    marginBottom: 20,
  },
  cardBoxInlineLabel: {
    fontSize: 16,
    color: "#000000",
    fontWeight: "500",
    marginRight: 10,
  },
  cardBoxInputFieldWide: {
    flex: 1,
    height: 38,
    borderWidth: 1.5,
    borderColor: "#000000",
    borderRadius: 12,
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    color: "#000000",
    fontSize: 16,
  },
  inlineCardDateCvvRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  cardInlineSegment: {
    flexDirection: "row",
    alignItems: "center",
    width: "48%",
  },
  cardBoxInputFieldShort: {
    flex: 1,
    height: 38,
    borderWidth: 1.5,
    borderColor: "#000000",
    borderRadius: 12,
    backgroundColor: "#ffffff",
    paddingHorizontal: 10,
    color: "#000000",
    fontSize: 15,
    textAlign: "center",
  },
  debitCreditSelectorPill: {
    width: "100%",
    backgroundColor: "#dcdde1",
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#b2bec3",
    marginBottom: 35,
  },
  selectorPillLeftBlock: { flexDirection: "row", alignItems: "center" },
  pillCardIcon: { fontSize: 22, marginRight: 12 },
  pillCardText: { fontSize: 16, fontWeight: "500", color: "#000000" },
  pillChevronIcon: { fontSize: 18, fontWeight: "bold", color: "#000000" },
  cardSubmitActionButton: {
    width: "100%",
    backgroundColor: "#1b3a6e",
    borderRadius: 20,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 40,
  },
  cardSubmitButtonText: { color: "#ffffff", fontSize: 24, fontWeight: "bold" },
  biometricOuterFrameZone: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  fingerprintGraphicTarget: {
    width: 65,
    height: 65,
    borderWidth: 2,
    borderColor: "#000000",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f8f9fa",
  },
  fingerprintGraphicIcon: { fontSize: 32, color: "#000000" },

  transferContainer: { flex: 1, backgroundColor: "#f8f9fa" },
  transferHeaderZone: {
    width: "100%",
    paddingTop: 60,
    paddingBottom: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1.5,
    borderColor: "#000000",
    backgroundColor: "#f8f9fa",
    paddingHorizontal: 16,
  },
  backArrowTouch: { paddingHorizontal: 8, paddingVertical: 4 },
  backArrowLabelText: { fontSize: 28, fontWeight: "bold", color: "#000000" },
  transferTitleText: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#000000",
    textAlign: "center",
  },
  headerRightSpacer: { width: 40 },
  transferFormScrollWrapper: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 60,
  },
  transferSectionFieldHeading: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#000000",
    marginBottom: 8,
    marginTop: 12,
  },
  accountSelectorCardBlock: {
    width: "100%",
    backgroundColor: "#dcdde1",
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#b2bec3",
    marginBottom: 16,
  },
  accountCardLeftContents: { flexDirection: "row", alignItems: "center" },
  cardVisualGraphicIcon: { fontSize: 24, marginRight: 12 },
  accountNameDisplayLabel: {
    fontSize: 16,
    fontWeight: "500",
    color: "#000000",
  },
  accountBalanceDisplayValue: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#000000",
  },
  accountBalanceRight: { flexDirection: "row", alignItems: "center" },
  accountSwapChevron: { fontSize: 16, fontWeight: "bold", marginLeft: 8, color: "#7f8c8d" },
  transferFormInputFieldElement: {
    width: "100%",
    height: 48,
    borderWidth: 1.5,
    borderColor: "#000000",
    borderRadius: 14,
    backgroundColor: "#ffffff",
    paddingHorizontal: 14,
    color: "#000000",
    fontSize: 16,
    marginBottom: 20,
  },
  transferExecutionButton: {
    width: "100%",
    backgroundColor: "#1b3a6e",
    borderRadius: 22,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
  },
  transferExecutionButtonText: {
    color: "#ffffff",
    fontSize: 24,
    fontWeight: "bold",
  },

  myCardsContainer: { flex: 1, backgroundColor: "#f8f9fa" },
  myCardsHeaderZone: {
    width: "100%",
    paddingTop: 60,
    paddingBottom: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1.5,
    borderColor: "#000000",
    backgroundColor: "#f8f9fa",
    paddingHorizontal: 16,
  },
  myCardsTitleText: { fontSize: 24, fontWeight: "bold", color: "#000000" },
  addCardButtonHeaderTouch: { paddingHorizontal: 6, paddingVertical: 2 },
  headerPlusIconGraphic: { fontSize: 30, fontWeight: "500", color: "#000000" },
  myCardsScrollWrapper: {
    paddingHorizontal: 20,
    paddingTop: 30,
    paddingBottom: 60,
  },
  stackedCardsWalletLayout: {
    width: "100%",
    alignItems: "center",
    position: "relative",
    height: 300,
  },
  baseVisualCardStructure: {
    width: "100%",
    height: 185,
    borderRadius: 24,
    padding: 24,
    justifyContent: "space-between",
    position: "absolute",
    left: 0,
    right: 0,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  fnbCardBackgroundLayer: {
    backgroundColor: "#111111",
    top: 0,
    zIndex: 1,
    transform: [{ scale: 0.96 }],
  },
  absaCardForegroundLayer: { backgroundColor: "#d63031", top: 55, zIndex: 2 },
  cardTopBrandingRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    width: "100%",
  },
  fnbBrandTextLabel: {
    color: "#ffffff",
    fontSize: 22,
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
  cardAccountTypeSubtitle: {
    color: "#bdc3c7",
    fontSize: 13,
    marginTop: 2,
    fontWeight: "500",
  },
  cardBalanceText: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "bold",
    marginTop: 10,
  },
  cardBalanceCaption: {
    color: "#dcdde1",
    fontSize: 11,
    fontWeight: "500",
    marginTop: 2,
  },
  fnbTreeGraphicLogo: { fontSize: 28 },
  absaCircleBrandLogoBadge: {
    borderWidth: 1.5,
    borderColor: "#ffffff",
    borderRadius: 25,
    paddingHorizontal: 12,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  absaLogoInlineText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
  contactlessWaveGraphicIcon: { fontSize: 24, color: "#ffffff" },
  cardBottomDetailsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  cardMaskedNumbersLabel: {
    color: "#ffffff",
    fontSize: 18,
    letterSpacing: 2,
    fontWeight: "500",
  },
  visaNetworkTextLogo: {
    color: "#ffffff",
    fontSize: 24,
    fontWeight: "bold",
    fontStyle: "italic",
    letterSpacing: 1,
  },
  linkedCardsSectionHeading: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#000000",
    marginTop: 24,
    marginBottom: 12,
    width: "100%",
  },
  linkedCardsEmptyText: {
    fontSize: 13,
    color: "#7f8c8d",
    width: "100%",
  },
  linkedCardRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#ffffff",
    borderWidth: 1.5,
    borderColor: "#000000",
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
  },
  linkedCardLeftBlock: { flexDirection: "row", alignItems: "center", gap: 12 },
  linkedCardIcon: { fontSize: 24 },
  linkedCardNumberText: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#000000",
  },
  linkedCardMetaText: {
    fontSize: 12,
    color: "#7f8c8d",
    marginTop: 2,
    fontWeight: "500",
  },
  linkedCardTypeBadge: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#54a0ff",
  },

  redeemContainer: { flex: 1, backgroundColor: "#f8f9fa" },
  redeemHeaderZone: {
    width: "100%",
    paddingTop: 60,
    paddingBottom: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1.5,
    borderColor: "#000000",
    backgroundColor: "#f8f9fa",
    paddingHorizontal: 16,
  },
  redeemTitleText: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#000000",
    textAlign: "center",
  },
  redeemFormScrollWrapper: {
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 60,
  },
  redeemSectionFieldHeading: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#000000",
    marginBottom: 10,
    marginTop: 14,
  },
  customSelectorDropdownRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 10,
    gap: 6,
  },
  dropdownPillOption: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderWidth: 1.5,
    borderColor: "#000000",
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  dropdownPillActive: { backgroundColor: "#54a0ff", borderColor: "#000000" },
  dropdownPillText: { fontSize: 12, fontWeight: "bold", color: "#000000" },
  dropdownPillTextActive: { color: "#ffffff" },
  redeemFormInputFieldElement: {
    width: "100%",
    height: 46,
    borderWidth: 1.5,
    borderColor: "#000000",
    borderRadius: 12,
    backgroundColor: "#ffffff",
    paddingHorizontal: 14,
    color: "#000000",
    fontSize: 15,
    marginBottom: 12,
  },
  accountCardBlockSelected: { borderColor: "#54a0ff", borderWidth: 2 },
  customRadioBubble: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: "#000000",
    marginRight: 12,
    backgroundColor: "#ffffff",
  },
  customRadioBubbleChecked: { backgroundColor: "#54a0ff" },
  verifiedTextBadge: { fontSize: 11, fontWeight: "bold", color: "#2ecc71" },
  redeemAccountRightBlock: { alignItems: "flex-end" },
  redeemAccountBalanceText: {
    fontSize: 12,
    color: "#7f8c8d",
    fontWeight: "600",
    marginTop: 2,
  },
  redeemExecutionButton: {
    width: "100%",
    backgroundColor: "#1b3a6e",
    borderRadius: 22,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 25,
  },
  redeemExecutionButtonText: {
    color: "#ffffff",
    fontSize: 22,
    fontWeight: "bold",
  },

  txContainer: { flex: 1, backgroundColor: "#f8f9fa" },
  txHeaderZone: {
    width: "100%",
    paddingTop: 60,
    paddingBottom: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1.5,
    borderColor: "#000000",
    backgroundColor: "#f8f9fa",
    paddingHorizontal: 16,
  },
  txTitleText: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#000000",
    textAlign: "center",
  },
  txAccountFilterTabBarRow: {
    flexDirection: "row",
    borderBottomWidth: 1.5,
    borderColor: "#000000",
    backgroundColor: "#ffffff",
  },
  txAccountFilterTabButton: {
    flex: 1,
    paddingVertical: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  txAccountFilterTabButtonActive: {
    borderBottomWidth: 4,
    borderBottomColor: "#54a0ff",
  },
  txAccountFilterTabText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#7f8c8d",
  },
  txAccountFilterTabTextActive: { color: "#000000" },
  txActiveSectionLabelFrame: {
    width: "100%",
    backgroundColor: "#eaecee",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderColor: "#bdc3c7",
  },
  txActiveSectionLabelText: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#2c3e50",
    letterSpacing: 0.5,
  },
  txListScrollWrapper: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 60,
  },
  txItemRowContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#ffffff",
    borderWidth: 1.5,
    borderColor: "#000000",
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
  },
  txItemLeftMetaBlock: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    gap: 14,
  },
  txItemStatusSymbolEmoji: { fontSize: 24 },
  txItemDescriptionMainTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#000000",
  },
  txItemLocationSubtitle: {
    fontSize: 13,
    color: "#7f8c8d",
    marginTop: 2,
    fontWeight: "500",
  },
  txItemTimestampString: {
    fontSize: 11,
    color: "#bdc3c7",
    marginTop: 4,
    fontWeight: "500",
  },
  txItemAmountValueTextInbound: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#2ecc71",
  },
  txItemAmountValueTextOutbound: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#e74c3c",
  },

  // RESPONSIVE ANALYTICS STYLING BLOCKS
  analyticsMainContainer: { flex: 1, backgroundColor: "#eaecee" },
  analyticsHeaderZone: {
    width: "100%",
    paddingTop: 60,
    paddingBottom: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1.5,
    borderColor: "#000000",
    backgroundColor: "#ffffff",
    paddingHorizontal: 16,
  },
  analyticsTitleText: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#000000",
    textAlign: "center",
  },
  periodFilterToggleRow: {
    flexDirection: "row",
    backgroundColor: "#ffffff",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderColor: "#bdc3c7",
    gap: 10,
  },
  periodTogglePill: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f2f4f4",
    borderWidth: 1,
    borderColor: "#bdc3c7",
  },
  periodTogglePillActive: {
    backgroundColor: "#1b3a6e",
    borderColor: "#1b3a6e",
  },
  periodToggleText: { fontSize: 14, fontWeight: "600", color: "#7f8c8d" },
  periodToggleTextActive: { color: "#ffffff" },
  analyticsScrollWrapper: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 100,
  },
  analyticsNumericalSummaryCard: {
    backgroundColor: "#ffffff",
    borderWidth: 1.5,
    borderColor: "#000000",
    borderRadius: 16,
    padding: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  numericalMetricBlock: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  metricSummaryLabel: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#7f8c8d",
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  metricSummaryValueGreen: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#2ecc71",
  },
  metricSummaryValueRed: { fontSize: 15, fontWeight: "bold", color: "#e74c3c" },
  metricSummaryValueBlue: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#2980b9",
  },
  verticalDividerLine: {
    width: 1.5,
    height: "70%",
    backgroundColor: "#bdc3c7",
  },
  chartCanvasContainerCard: {
    backgroundColor: "#ffffff",
    borderWidth: 1.5,
    borderColor: "#000000",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  canvasInsideLabelHeader: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#2c3e50",
    marginBottom: 20,
    letterSpacing: 0.5,
    textAlign: "center",
  },
  chartBarGraphAxisRow: { flexDirection: "row", height: 200, width: "100%" },
  graphYAxisScalesColumn: {
    width: 40,
    height: "100%",
    justifyContent: "space-between",
    paddingBottom: 25,
    borderRightWidth: 1,
    borderColor: "#bdc3c7",
  },
  yAxisScaleLabelText: { fontSize: 11, fontWeight: "600", color: "#7f8c8d" },
  graphBarsMainPlotZone: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "flex-end",
    paddingLeft: 10,
  },
  individualBarColumnGrouping: {
    alignItems: "center",
    width: "28%",
    height: "100%",
    justifyContent: "flex-end",
  },
  barVerticalGrowthTrackEmptySpace: {
    flex: 1,
    width: "100%",
    justifyContent: "flex-end",
    alignItems: "center",
    paddingBottom: 6,
  },
  liveColorBarGrowthPill: { width: 32, borderRadius: 6 },
  revenueBarColor: { backgroundColor: "#2ecc71" },
  expensesBarColor: { backgroundColor: "#e74c3c" },
  profitBarColor: { backgroundColor: "#2980b9" },
  barBottomLabelIndicator: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#000000",
    marginTop: 4,
  },
  efficiencyRatioDetailsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  efficiencyRatioLabelText: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#000000",
  },
  efficiencyRatioValuePercentageText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#2980b9",
  },

  // --- "Grow Your Business" dashboard section (QR Pay / Funding entry points) ---
  growSectionHeading: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#000000",
    marginBottom: 12,
  },
  growCardsRow: { flexDirection: "row", gap: 12 },
  growActionCard: {
    flex: 1,
    backgroundColor: "#1b3a6e",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1.5,
    borderColor: "#000000",
  },
  growActionCardAlt: {
    flex: 1,
    backgroundColor: "#dfb76c",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1.5,
    borderColor: "#000000",
  },
  growCardTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  growActionIcon: { fontSize: 26 },
  growComingSoonBadge: {
    backgroundColor: "rgba(255,255,255,0.92)",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  growComingSoonBadgeText: {
    fontSize: 9,
    fontWeight: "bold",
    color: "#1b3a6e",
    letterSpacing: 0.5,
  },
  growActionTitle: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#ffffff",
    marginBottom: 4,
  },
  growActionSubtitle: { fontSize: 11, color: "#dcdde1", lineHeight: 15 },
  growActionTitleAlt: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#1b3a6e",
    marginBottom: 4,
  },
  growActionSubtitleAlt: { fontSize: 11, color: "#5c4a1f", lineHeight: 15 },

  // --- QR Pay screen ---
  qrCodeWrapper: {
    alignSelf: "center",
    backgroundColor: "#ffffff",
    padding: 12,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#000000",
    marginVertical: 20,
  },
  qrGridRow: { flexDirection: "row" },
  qrCell: { width: 16, height: 16 },
  qrCellFilled: { backgroundColor: "#000000" },
  qrCellEmpty: { backgroundColor: "#ffffff" },
  qrCaptionText: {
    fontSize: 13,
    color: "#7f8c8d",
    textAlign: "center",
    marginBottom: 20,
  },
  qrStatusPill: {
    alignSelf: "center",
    backgroundColor: "#eaecee",
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#bdc3c7",
  },
  qrStatusText: { fontSize: 13, fontWeight: "600", color: "#7f8c8d" },
  recentQrHeading: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#000000",
    marginTop: 10,
    marginBottom: 12,
  },

  // --- Business Funding screen ---
  fundingScoreWrapper: { alignItems: "center", marginVertical: 20 },
  fundingEligibleAmountText: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#1b3a6e",
    marginTop: 8,
  },
  fundingEligibleLabel: {
    fontSize: 13,
    color: "#7f8c8d",
    textAlign: "center",
    marginTop: 14,
    marginBottom: 4,
    paddingHorizontal: 20,
  },
  presetAmountRow: { flexDirection: "row", gap: 10, marginBottom: 20 },
  presetAmountPill: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderWidth: 1.5,
    borderColor: "#000000",
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
  },
  presetAmountPillActive: { backgroundColor: "#54a0ff" },
  presetAmountPillText: { fontSize: 13, fontWeight: "bold", color: "#000000" },
  presetAmountPillTextActive: { color: "#ffffff" },
  presetAmountPillAmountText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#7f8c8d",
    marginTop: 3,
  },
  presetAmountPillAmountTextActive: { color: "#eaf4ff" },
  fundingSelectedAmountText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#000000",
    textAlign: "center",
    marginBottom: 20,
  },
  fundingDisclaimerText: {
    fontSize: 12,
    color: "#7f8c8d",
    fontStyle: "italic",
    textAlign: "center",
    marginBottom: 20,
    lineHeight: 17,
  },
});

export default styles;
